### ISSUE TITLE
sails.getDatastore is not a function

### ISSUE THREAD

**Issue by tlhunter** [balderdashy/sails-docs#1105] opened 2018-12-03 19:24 UTC
In this document:
https://github.com/balderdashy/sails-docs/blob/master/reference/application/sails.getDatastore.md

A reference is made to `sails.getDatastore(nameOfDatastore)`. However, running that code results in the following error:

```
Details:TypeError: sails.getDatastore is not a function
```

If some additional configuration needs to be set before this method is available I'd recommend specifying so in that document.

**Comment by rachaelshaw** [comment] 2019-02-19 23:31
@tlhunter do you have any version info/other details you can share, in case it helps diagnose what's going on? What version of sails-hook-orm are you using?

I just lifted with `sails console` in a newly-generated project with no additional configuration (on sails-hook-orm v2.1.1), then ran `sails.getDatastore()` in the terminal and got:
```
{ name: 'default',
  config: { schema: false, dir: '.tmp/localDiskDb', adapter: 'sails-disk' },
  leaseConnection: [Function],
  sendStatement: [Function],
  sendNativeQuery: [Function],
  transaction: [Function] }
```

**Comment by tlhunter** [comment] 2019-02-20 07:08
Unfortunately I haven't used sails since filing this issue and I no longer have details.

It might have been something like the code failed when run synchronously in the top level of a file, but it succeeded when run run in an asynchronous callback?

**Comment by rachaelshaw** [comment] 2019-02-20 14:53
@tlhunter thanks for the follow up! Closing this since there's no way to get enough info to reproduce the issue

**Closed by rachaelshaw** 2019-02-20 14:53 UTC
