### ISSUE TITLE
Who is Timothy the Monkey?

### ISSUE THREAD

**Issue by brettimus** [balderdashy/sails-docs#524] opened 2015-07-17 18:25 UTC
[The concept page on models](http://sailsjs.org/documentation/concepts/models-and-orm/models) has a link to a story about "Timothy the Monkey." 

Unfortunately, this link does not go anywhere! I want to know about Tim!! My google search was fruitless.

:monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:

**Comment by rachaelshaw** [comment] 2015-07-20 15:36
Duplicate of #400 -- closing this so we can move all discussion to that issue.
Timothy would have wanted it that way.

**Closed by rachaelshaw** 2015-07-20 15:36 UTC

**Comment by brettimus** [comment] 2015-07-20 18:34
Should have done a search- my b. :see_no_evil: 

Send Tim my regards
